### ISSUE TITLE
Getting things up and running

### ISSUE THREAD

**Issue by cmacht** [vanita5/TwittnukerPushServer2#1]
Hej, really like Twittnuker as a client but getting Push Notifications to work is very unintuitive. Did I understand correctly that having Node.js on my own server is required before I can do anything with these JS files?

**Comment by eliah-w** [comment]
Right, you need to have node installed

**Comment by cmacht** [comment]
Thanks for the quick reply! After figuring out how to work with Node.js, I've set up the server and Twittnuker is connected to it. This link helped:

https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-14-04
